spring:
  jpa:
    properties:
      hibernate:
        default_schema: public
        hbm2ddl:
          auto: update
  docker:
    compose:
      file: src/main/docker/compose.yaml
      enabled: true
      lifecycle-management: start_only