name: dades_adventure
services:
  postgres:
    container_name: dades_adventure_db
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=dades_adventure'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=myuser'
    ports:
      - '5432:5432'
